[package]
name = "check_av1_encode"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
serde_json = "1.0.96"
rayon = "1.7.0"
